### ISSUE TITLE
Feature request: log paste events in exam client

### ISSUE THREAD

**Issue by davidwagner** [Cal-CS-61A-Staff/cs61a-apps#74]
Copied from https://github.com/Cal-CS-61A-Staff/examtool-web/issues/16:

For some cheating investigations, it would be useful to know whether the student has pasted anything into the page. This could plausibly be done by hooking the paste event and logging each paste event, along with what text was pasted. This would not be foolproof but it might be helpful in detecting or investigating some cheating cases.

**Comment by rahularya50** [comment]
Resolved with apps/270.
