### ISSUE TITLE
Feature request: log copy events in exam client

### ISSUE THREAD

**Issue by davidwagner** [Cal-CS-61A-Staff/cs61a-apps#75]
Copied from https://github.com/Cal-CS-61A-Staff/examtool-web/issues/17:

For some cheating investigations, it would be useful to know whether the student has copied anything from the page (e.g., to share with others). This could plausibly be done by hooking the copy event and logging each copy event, along with what text was copied. This would not be foolproof but it might be helpful in detecting or investigating some cheating cases.

**Comment by rahularya50** [comment]
Resolved with apps/270.
