### ISSUE TITLE
Examtool cheaters misses a lot of cheating

### ISSUE THREAD

**Issue by davidwagner** [Cal-CS-61A-Staff/cs61a-apps#76]
I've been told that `examtool cheaters` only reports the first instance of cheating on each exam.  The problem is that, if this first instance happens to be a false positive, then we fail to detect any other cheating on the exam.  Depending on exam design, false positives might not be unusual.

It would be helpful to report all instances of cheating.

**Comment by rahularya50** [comment]
Fixed - this is actually probably the issue from #77
