### ISSUE TITLE
Bug: false negative with examtool cheaters

### ISSUE THREAD

**Issue by davidwagner** [Cal-CS-61A-Staff/cs61a-apps#77]
With examtool 2.0.15, `examtool cheaters` reported a mismatch in one answer, where the answer used a different alternative from the one listed in the question.  This appears to be correct, as verified with `examtool substitutions` and by looking at their specific answer.

With examtool 2.1.7, `examtool cheaters` no longer detects anything for that student.  This appears to be a false negative.  I'm not sure how to narrow down why it failed to detect the problem.  Any ideas on how to troubleshoot why it failed?

(Overall, examtool 2.1.7 produced about 6x less output from the cheaters subcommand than 2.0.15 did.  I don't know how to assess that in aggregate, but I can verify the specific instance mentioned above.)

**Comment by rahularya50** [comment]
Thanks for reporting this! I'll take a look now

**Comment by rahularya50** [comment]
Would you mind trying the examtool version in https://github.com/Cal-CS-61A-Staff/cs61a-apps/pull/80 and seeing whether it resolves your issue? If you click on the PyPI link, you'll get a command that lets you install the pre-release via pip.
